src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use App\Repository\UtilisateurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UtilisateurRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
class Utilisateur implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    #[Assert\Email(message: "Adresse Mail au mauvais format.")]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 60)]
    private ?string $nom = null;

    #[ORM\Column(length: 60)]
    private ?string $prenom = null;

    #[ORM\Column(length: 60)]
    private ?string $poste = null;

    #[ORM\OneToMany(targetEntity: EmpruntVehicule::class, mappedBy: 'emprunteur')]
    private Collection $empruntVehicules;

    #[ORM\OneToMany(targetEntity: EmpruntSalle::class, mappedBy: 'Emprunteur')]
    private Collection $empruntSalles;

    #[ORM\OneToMany(targetEntity: EmpruntMateriel::class, mappedBy: 'emprunteur')]
    private Collection $empruntMateriels;

    #[ORM\ManyToOne(fetch: 'EAGER', inversedBy: 'utilisateurs')]
    private ?Centre $Centre;

    public function __construct()
    {
        $this->empruntVehicules = new ArrayCollection();
        $this->empruntSalles = new ArrayCollection();
        $this->empruntMateriels = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getPoste(): ?string
    {
        return $this->poste;
    }

    public function setPoste(string $poste): static
    {
        $this->poste = $poste;

        return $this;
    }

    /**
     * @return Collection<int, EmpruntVehicule>
     */
    public function getEmpruntVehicules(): Collection
    {
        return $this->empruntVehicules;
    }

    public function addEmpruntVehicule(EmpruntVehicule $empruntVehicule): static
    {
        if (!$this->empruntVehicules->contains($empruntVehicule)) {
            $this->empruntVehicules->add($empruntVehicule);
            $empruntVehicule->setEmprunteur($this);
        }

        return $this;
    }

    public function removeEmpruntVehicule(EmpruntVehicule $empruntVehicule): static
    {
        if ($this->empruntVehicules->removeElement($empruntVehicule)) {
            // set the owning side to null (unless already changed)
            if ($empruntVehicule->getEmprunteur() === $this) {
                $empruntVehicule->setEmprunteur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, EmpruntSalle>
     */
    public function getEmpruntSalles(): Collection
    {
        return $this->empruntSalles;
    }

    public function addEmpruntSalle(EmpruntSalle $empruntSalle): static
    {
        if (!$this->empruntSalles->contains($empruntSalle)) {
            $this->empruntSalles->add($empruntSalle);
            $empruntSalle->setEmprunteur($this);
        }

        return $this;
    }

    public function removeEmpruntSalle(EmpruntSalle $empruntSalle): static
    {
        if ($this->empruntSalles->removeElement($empruntSalle)) {
            // set the owning side to null (unless already changed)
            if ($empruntSalle->getEmprunteur() === $this) {
                $empruntSalle->setEmprunteur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, EmpruntMateriel>
     */
    public function getEmpruntMateriels(): Collection
    {
        return $this->empruntMateriels;
    }

    public function addEmpruntMateriel(EmpruntMateriel $empruntMateriel): static
    {
        if (!$this->empruntMateriels->contains($empruntMateriel)) {
            $this->empruntMateriels->add($empruntMateriel);
            $empruntMateriel->setEmprunteur($this);
        }

        return $this;
    }

    public function removeEmpruntMateriel(EmpruntMateriel $empruntMateriel): static
    {
        if ($this->empruntMateriels->removeElement($empruntMateriel)) {
            // set the owning side to null (unless already changed)
            if ($empruntMateriel->getEmprunteur() === $this) {
                $empruntMateriel->setEmprunteur(null);
            }
        }

        return $this;
    }

    public function getCentre(): ?Centre
    {
        return $this->Centre;
    }

    public function setCentre(?Centre $Centre): static
    {
        $this->Centre = $Centre;

        return $this;
    }

}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Entity\Utilisateur;
use App\Form\RegistrationFormType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    #[Route(path: '/login', name: 'app_login')]
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // if ($this->getUser()) {
        //     return $this->redirectToRoute('target_path');
        // }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    #[Route(path: '/logout', name: 'app_logout')]
    public function logout(): void
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }

    #[Route(path: '/inscription', name: 'app_register')]
    public function inscription(Request $request, UserPasswordHasherInterface $userPasswordHasher, EntityManagerInterface $entityManager, Utilisateur $user): Response
    {
        $user = new Utilisateur();
        $form = $this->createForm(RegistrationFormType::class,$user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            $user->setPassword(
                $userPasswordHasher->hashPassword(
                    $user,
                    $form->get('password')->getData()
                )
            );

            $entityManager->persist($user);
            $entityManager->flush($user);

            $this->addFlash("succes","Utilisateur ajouté avec succès.");
            return $this->redirectToRoute('app_admin_profil');
        } else {
            $this->addFlash("erreur", "Erreur à l'ajout de l'utilisateur.");
        }
        return $this->render('security/register.html.twig', ['registrationForm' => $form]);
    }
}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}

{% block body %}
    <div class="login-container">
<form method="post" class="login-card">
    {% if error %}
        <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}

    {% if app.user %}
        <div class="mb-3">
            You are logged in as {{ app.user.userIdentifier }}, <a href="{{ path('app_logout') }}">Logout</a>
        </div>
    {% endif %}

    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
    <label for="inputEmail">Email</label>
    <input type="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control" autocomplete="email" required autofocus>
    <label for="inputPassword">Password</label>
    <input type="password" name="password" id="inputPassword" class="form-control" autocomplete="current-password" required>

    <input type="hidden" name="_csrf_token"
           value="{{ csrf_token('authenticate') }}"
    >

    <div class="checkbox mb-3">
        <label>
            <input type="checkbox" name="_remember_me"> Remember me
        </label>
    </div>

    <button class="btn btn-lg btn-primary" type="submit">
        Sign in
    </button>
</form>
    </div>
{% endblock %}

templates/security/register.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inscription{% endblock %}

{% block body %}

        {{ form_start(registrationForm) }}
    <div class="inscription_form">
        <h1>Ajouter un utilisateur :</h1>
        {% for message in app.flashes('error')  %}
            <div class="erreur">{{ message }}</div>
        {% endfor %}
        {% for message in app.flashes('success')  %}
            <div class="succes">{{ message }}</div>
        {% endfor %}
        {{ form_label(registrationForm.email) }}
        {{ form_widget(registrationForm.email) }}
        {{ form_label(registrationForm.nom) }}
        {{ form_widget(registrationForm.nom) }}
        {{ form_label(registrationForm.prenom) }}
        {{ form_widget(registrationForm.prenom) }}
        {{ form_label(registrationForm.poste) }}
        {{ form_widget(registrationForm.poste) }}
        {{ form_label(registrationForm.password) }}
        {{ form_widget(registrationForm.password) }}
        {{ form_label(registrationForm.centre) }}
        {{ form_widget(registrationForm.centre) }}
        {{ form_label(registrationForm.roles) }}
        {{ form_widget(registrationForm.roles) }}
        <button>Inscrire</button>
    </div>
        {{ form_end(registrationForm) }}

{% endblock %}